packageExtensions:
  "@devexperts/remote-data-ts@*":
    peerDependenciesMeta:
      monocle-ts:
        optional: true
      newtype-ts:
        optional: true
  "@mdx-js/loader@*":
    peerDependenciesMeta:
      react:
        optional: true
  "@storybook/addon-info@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/addons@*":
    peerDependenciesMeta:
      regenerator-runtime:
        optional: true
  "@storybook/api@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "@storybook/core@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@storybook/react@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@types/testing-library__react@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@types/testing-library__user-event@*":
    peerDependenciesMeta:
      "@testing-library/dom":
        optional: true
  connected-react-router@*:
    peerDependenciesMeta:
      seamless-immutable:
        optional: true
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  react-dev-utils@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  react-docgen-typescript-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  styled-components@*:
    peerDependenciesMeta:
      react-is:
        optional: true
  terser@*:
    dependencies:
      acorn: "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"
      json-schema: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpFallbackMode: dependencies-only

pnpMode: loose

preferInteractive: true

yarnPath: .yarn/releases/yarn-sources.cjs
