packageExtensions:
  "@mdx-js/loader@*":
    peerDependenciesMeta:
      react:
        optional: true
  "@storybook/addon-info@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/addons@*":
    peerDependenciesMeta:
      regenerator-runtime:
        optional: true
  "@storybook/api@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "@storybook/core@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@storybook/react@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@types/testing-library__react@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@types/testing-library__user-event@*":
    peerDependenciesMeta:
      "@testing-library/dom":
        optional: true
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  react-dev-utils@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  styled-components@*:
    peerDependenciesMeta:
      react-is:
        optional: true
  terser@*:
    dependencies:
      acorn: "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"
      json-schema: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferInteractive: true

progressBarStyle: simba

yarnPath: .yarn/releases/yarn-3.1.0.cjs
