// flow-typed signature: 361543062eccbb5178943d33a0b361c3
// flow-typed version: <<STUB>>/@loadable/babel-plugin_v^5.10.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@loadable/babel-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@loadable/babel-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@loadable/babel-plugin/lib/index' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/lib/properties/chunkName' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/lib/properties/isReady' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/lib/properties/requireAsync' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/lib/properties/requireSync' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/lib/properties/resolve' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/lib/util' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/index' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/index.test' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/properties/chunkName' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/properties/isReady' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/properties/requireAsync' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/properties/requireSync' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/properties/resolve' {
  declare module.exports: any;
}

declare module '@loadable/babel-plugin/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@loadable/babel-plugin/lib/index.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/lib/index'>;
}
declare module '@loadable/babel-plugin/lib/properties/chunkName.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/lib/properties/chunkName'>;
}
declare module '@loadable/babel-plugin/lib/properties/isReady.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/lib/properties/isReady'>;
}
declare module '@loadable/babel-plugin/lib/properties/requireAsync.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/lib/properties/requireAsync'>;
}
declare module '@loadable/babel-plugin/lib/properties/requireSync.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/lib/properties/requireSync'>;
}
declare module '@loadable/babel-plugin/lib/properties/resolve.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/lib/properties/resolve'>;
}
declare module '@loadable/babel-plugin/lib/util.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/lib/util'>;
}
declare module '@loadable/babel-plugin/src/index.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/index'>;
}
declare module '@loadable/babel-plugin/src/index.test.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/index.test'>;
}
declare module '@loadable/babel-plugin/src/properties/chunkName.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/properties/chunkName'>;
}
declare module '@loadable/babel-plugin/src/properties/isReady.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/properties/isReady'>;
}
declare module '@loadable/babel-plugin/src/properties/requireAsync.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/properties/requireAsync'>;
}
declare module '@loadable/babel-plugin/src/properties/requireSync.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/properties/requireSync'>;
}
declare module '@loadable/babel-plugin/src/properties/resolve.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/properties/resolve'>;
}
declare module '@loadable/babel-plugin/src/util.js' {
  declare module.exports: $Exports<'@loadable/babel-plugin/src/util'>;
}
