// flow-typed signature: 0a92ec3126c4b657343218b7f4e23da2
// flow-typed version: <<STUB>>/@loadable/webpack-plugin_v^5.7.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@loadable/webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@loadable/webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@loadable/webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@loadable/webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'@loadable/webpack-plugin/lib/index'>;
}
