// flow-typed signature: c3b2f343a3101ef0a9c607129e005bea
// flow-typed version: <<STUB>>/core-util-is_v^1.0.2/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'core-util-is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'core-util-is' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'core-util-is/lib/util' {
  declare module.exports: any;
}

declare module 'core-util-is/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'core-util-is/lib/util.js' {
  declare module.exports: $Exports<'core-util-is/lib/util'>;
}
declare module 'core-util-is/test.js' {
  declare module.exports: $Exports<'core-util-is/test'>;
}
