// flow-typed signature: b8eecf3062d4838d749a2aeb6d51db0b
// flow-typed version: <<STUB>>/eslint-plugin-varspacing_v^1.2.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-varspacing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-varspacing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-varspacing/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/lib/rules/var-spacing.rule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/lib/util/checkOperator' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/lib/util/columnComputation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/lib/util/findNextPunctuators' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/lib/util/fixer' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/lib/util/registerToken' {
  declare module.exports: any;
}

declare module 'eslint-plugin-varspacing/lib/util/validatePunctuators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-varspacing/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/coverage/lcov-report/prettify'>;
}
declare module 'eslint-plugin-varspacing/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/coverage/lcov-report/sorter'>;
}
declare module 'eslint-plugin-varspacing/index' {
  declare module.exports: $Exports<'eslint-plugin-varspacing'>;
}
declare module 'eslint-plugin-varspacing/index.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing'>;
}
declare module 'eslint-plugin-varspacing/lib/rules/var-spacing.rule.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/lib/rules/var-spacing.rule'>;
}
declare module 'eslint-plugin-varspacing/lib/util/checkOperator.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/lib/util/checkOperator'>;
}
declare module 'eslint-plugin-varspacing/lib/util/columnComputation.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/lib/util/columnComputation'>;
}
declare module 'eslint-plugin-varspacing/lib/util/findNextPunctuators.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/lib/util/findNextPunctuators'>;
}
declare module 'eslint-plugin-varspacing/lib/util/fixer.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/lib/util/fixer'>;
}
declare module 'eslint-plugin-varspacing/lib/util/registerToken.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/lib/util/registerToken'>;
}
declare module 'eslint-plugin-varspacing/lib/util/validatePunctuators.js' {
  declare module.exports: $Exports<'eslint-plugin-varspacing/lib/util/validatePunctuators'>;
}
