// flow-typed signature: 2370882c77d1da67a2ff0169c53b5fec
// flow-typed version: <<STUB>>/eslint-plugin-arca_v^0.8.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-arca'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-arca' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-arca/lib/constants' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/lib/rules/curly' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/lib/rules/import-align' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/lib/rules/import-ordering' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/lib/rules/melted-constructs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/lib/rules/newline-after-import-section' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/lib/rules/no-default-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/tests/lib/rules/curly' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/tests/lib/rules/import-align' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/tests/lib/rules/import-ordering' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/tests/lib/rules/melted-constructs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/tests/lib/rules/newline-after-import-section' {
  declare module.exports: any;
}

declare module 'eslint-plugin-arca/tests/lib/rules/no-default-export' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-arca/lib/constants.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/constants'>;
}
declare module 'eslint-plugin-arca/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/index'>;
}
declare module 'eslint-plugin-arca/lib/rules/curly.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/rules/curly'>;
}
declare module 'eslint-plugin-arca/lib/rules/import-align.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/rules/import-align'>;
}
declare module 'eslint-plugin-arca/lib/rules/import-ordering.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/rules/import-ordering'>;
}
declare module 'eslint-plugin-arca/lib/rules/melted-constructs.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/rules/melted-constructs'>;
}
declare module 'eslint-plugin-arca/lib/rules/newline-after-import-section.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/rules/newline-after-import-section'>;
}
declare module 'eslint-plugin-arca/lib/rules/no-default-export.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/lib/rules/no-default-export'>;
}
declare module 'eslint-plugin-arca/tests/lib/rules/curly.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/tests/lib/rules/curly'>;
}
declare module 'eslint-plugin-arca/tests/lib/rules/import-align.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/tests/lib/rules/import-align'>;
}
declare module 'eslint-plugin-arca/tests/lib/rules/import-ordering.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/tests/lib/rules/import-ordering'>;
}
declare module 'eslint-plugin-arca/tests/lib/rules/melted-constructs.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/tests/lib/rules/melted-constructs'>;
}
declare module 'eslint-plugin-arca/tests/lib/rules/newline-after-import-section.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/tests/lib/rules/newline-after-import-section'>;
}
declare module 'eslint-plugin-arca/tests/lib/rules/no-default-export.js' {
  declare module.exports: $Exports<'eslint-plugin-arca/tests/lib/rules/no-default-export'>;
}
