// flow-typed signature: 8d478d62460b6a992e435e41baa80d16
// flow-typed version: <<STUB>>/hard-source-webpack-plugin_v^0.13.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hard-source-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hard-source-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hard-source-webpack-plugin/lib/CacheAsset' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/CacheEnhancedResolve' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/CacheMd5' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/CacheModule' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/CacheModuleResolver' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/CacheSerializerFactory' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/ChalkLoggerPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/defaultConfigHash' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/envHash' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/ExcludeModulePlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/loggerFactory' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/ParallelLauncherPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/ParallelModulePlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/schema-4/_generate' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/schema-4/index' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerAppend' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerAppend2' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerAppend2Plugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerAppendPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerCacache' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerCacachePlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerFile' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerFilePlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerJson' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerJsonPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerLeveldb' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SerializerLeveldbPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SupportExtractTextPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SupportMiniCssExtractPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SystemArchetype' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SystemParity' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/SystemPruneCaches' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformAssetPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformBasicDependencyPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformBasicDependencyPluginLegacy' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformCompilationPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformConcatenationModulePlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformDependencyBlockPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformGeneratorPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformModuleAssetsPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformModuleErrorsPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformNormalModuleFactoryPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformNormalModulePlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformParserPlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/TransformSourcePlugin' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/bulk-fs-task' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/index' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/log-messages' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/Object.entries' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/Object.values' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/parity' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/plugin-compat' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/promisify' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/relate-context' {
  declare module.exports: any;
}

declare module 'hard-source-webpack-plugin/lib/util/serial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hard-source-webpack-plugin/index' {
  declare module.exports: $Exports<'hard-source-webpack-plugin'>;
}
declare module 'hard-source-webpack-plugin/index.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/CacheAsset.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/CacheAsset'>;
}
declare module 'hard-source-webpack-plugin/lib/CacheEnhancedResolve.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/CacheEnhancedResolve'>;
}
declare module 'hard-source-webpack-plugin/lib/CacheMd5.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/CacheMd5'>;
}
declare module 'hard-source-webpack-plugin/lib/CacheModule.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/CacheModule'>;
}
declare module 'hard-source-webpack-plugin/lib/CacheModuleResolver.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/CacheModuleResolver'>;
}
declare module 'hard-source-webpack-plugin/lib/CacheSerializerFactory.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/CacheSerializerFactory'>;
}
declare module 'hard-source-webpack-plugin/lib/ChalkLoggerPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/ChalkLoggerPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/defaultConfigHash.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/defaultConfigHash'>;
}
declare module 'hard-source-webpack-plugin/lib/envHash.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/envHash'>;
}
declare module 'hard-source-webpack-plugin/lib/ExcludeModulePlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/ExcludeModulePlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/loggerFactory.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/loggerFactory'>;
}
declare module 'hard-source-webpack-plugin/lib/ParallelLauncherPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/ParallelLauncherPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/ParallelModulePlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/ParallelModulePlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/schema-4/_generate.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/schema-4/_generate'>;
}
declare module 'hard-source-webpack-plugin/lib/schema-4/index.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/schema-4/index'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerAppend.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerAppend'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerAppend2.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerAppend2'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerAppend2Plugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerAppend2Plugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerAppendPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerAppendPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerCacache.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerCacache'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerCacachePlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerCacachePlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerFile.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerFile'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerFilePlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerFilePlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerJson.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerJson'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerJsonPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerJsonPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerLeveldb.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerLeveldb'>;
}
declare module 'hard-source-webpack-plugin/lib/SerializerLeveldbPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SerializerLeveldbPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SupportExtractTextPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SupportExtractTextPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SupportMiniCssExtractPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SupportMiniCssExtractPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/SystemArchetype.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SystemArchetype'>;
}
declare module 'hard-source-webpack-plugin/lib/SystemParity.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SystemParity'>;
}
declare module 'hard-source-webpack-plugin/lib/SystemPruneCaches.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/SystemPruneCaches'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformAssetPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformAssetPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformBasicDependencyPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformBasicDependencyPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformBasicDependencyPluginLegacy.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformBasicDependencyPluginLegacy'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformCompilationPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformCompilationPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformConcatenationModulePlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformConcatenationModulePlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformDependencyBlockPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformDependencyBlockPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformGeneratorPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformGeneratorPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformModuleAssetsPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformModuleAssetsPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformModuleErrorsPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformModuleErrorsPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformNormalModuleFactoryPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformNormalModuleFactoryPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformNormalModulePlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformNormalModulePlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformParserPlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformParserPlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/TransformSourcePlugin.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/TransformSourcePlugin'>;
}
declare module 'hard-source-webpack-plugin/lib/util/bulk-fs-task.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/bulk-fs-task'>;
}
declare module 'hard-source-webpack-plugin/lib/util/index.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/index'>;
}
declare module 'hard-source-webpack-plugin/lib/util/log-messages.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/log-messages'>;
}
declare module 'hard-source-webpack-plugin/lib/util/Object.entries.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/Object.entries'>;
}
declare module 'hard-source-webpack-plugin/lib/util/Object.values.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/Object.values'>;
}
declare module 'hard-source-webpack-plugin/lib/util/parity.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/parity'>;
}
declare module 'hard-source-webpack-plugin/lib/util/plugin-compat.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/plugin-compat'>;
}
declare module 'hard-source-webpack-plugin/lib/util/promisify.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/promisify'>;
}
declare module 'hard-source-webpack-plugin/lib/util/relate-context.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/relate-context'>;
}
declare module 'hard-source-webpack-plugin/lib/util/serial.js' {
  declare module.exports: $Exports<'hard-source-webpack-plugin/lib/util/serial'>;
}
