// flow-typed signature: 4f4ebe90cca303a074d78c8e02423fd2
// flow-typed version: <<STUB>>/html-webpack-exclude-assets-plugin_v0.0.7/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-exclude-assets-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-exclude-assets-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-webpack-exclude-assets-plugin/index' {
  declare module.exports: $Exports<'html-webpack-exclude-assets-plugin'>;
}
declare module 'html-webpack-exclude-assets-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-exclude-assets-plugin'>;
}
