// flow-typed signature: c0d63abc95ec3b33078fe4ab7ec8dbae
// flow-typed version: <<STUB>>/html-webpack-harddisk-plugin_v^1.0.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-harddisk-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-harddisk-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-webpack-harddisk-plugin/index' {
  declare module.exports: $Exports<'html-webpack-harddisk-plugin'>;
}
declare module 'html-webpack-harddisk-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-harddisk-plugin'>;
}
