// flow-typed signature: 866c300cbda191d3af1f7a4b0dc3eb5a
// flow-typed version: <<STUB>>/pug-html-loader_v^1.1.5/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-html-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-html-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-html-loader/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-html-loader/lib/index.js' {
  declare module.exports: $Exports<'pug-html-loader/lib/index'>;
}
