// flow-typed signature: 546c40134e41fed400b3de20b5867874
// flow-typed version: <<STUB>>/pug_v^2.0.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug/lib/index' {
  declare module.exports: any;
}

declare module 'pug/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug/lib/index.js' {
  declare module.exports: $Exports<'pug/lib/index'>;
}
declare module 'pug/register.js' {
  declare module.exports: $Exports<'pug/register'>;
}
