// flow-typed signature: 0f52fd0523617cae9d44ceb8edb76606
// flow-typed version: <<STUB>>/reflect-metadata_v^0.1.13/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reflect-metadata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reflect-metadata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reflect-metadata/docs/ecmarkup' {
  declare module.exports: any;
}

declare module 'reflect-metadata/Reflect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reflect-metadata/docs/ecmarkup.js' {
  declare module.exports: $Exports<'reflect-metadata/docs/ecmarkup'>;
}
declare module 'reflect-metadata/Reflect.js' {
  declare module.exports: $Exports<'reflect-metadata/Reflect'>;
}
