// flow-typed signature: 0650ee531ad5f4c9dba4a1062b5c1125
// flow-typed version: <<STUB>>/workbox-cli_v^4.3.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-cli/build/app' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/bin' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/assert-valid-sw-src' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/cleanup-stack-trace' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/constants' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/errors' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/help-text' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/logger' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/questions/ask-config-location' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/questions/ask-extensions-to-cache' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/questions/ask-questions' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/questions/ask-root-of-web-app' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/questions/ask-sw-dest' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/questions/ask-sw-src' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/read-config' {
  declare module.exports: any;
}

declare module 'workbox-cli/build/lib/run-wizard' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-cli/build/app.js' {
  declare module.exports: $Exports<'workbox-cli/build/app'>;
}
declare module 'workbox-cli/build/bin.js' {
  declare module.exports: $Exports<'workbox-cli/build/bin'>;
}
declare module 'workbox-cli/build/lib/assert-valid-sw-src.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/assert-valid-sw-src'>;
}
declare module 'workbox-cli/build/lib/cleanup-stack-trace.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/cleanup-stack-trace'>;
}
declare module 'workbox-cli/build/lib/constants.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/constants'>;
}
declare module 'workbox-cli/build/lib/errors.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/errors'>;
}
declare module 'workbox-cli/build/lib/help-text.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/help-text'>;
}
declare module 'workbox-cli/build/lib/logger.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/logger'>;
}
declare module 'workbox-cli/build/lib/questions/ask-config-location.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/questions/ask-config-location'>;
}
declare module 'workbox-cli/build/lib/questions/ask-extensions-to-cache.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/questions/ask-extensions-to-cache'>;
}
declare module 'workbox-cli/build/lib/questions/ask-questions.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/questions/ask-questions'>;
}
declare module 'workbox-cli/build/lib/questions/ask-root-of-web-app.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/questions/ask-root-of-web-app'>;
}
declare module 'workbox-cli/build/lib/questions/ask-sw-dest.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/questions/ask-sw-dest'>;
}
declare module 'workbox-cli/build/lib/questions/ask-sw-src.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/questions/ask-sw-src'>;
}
declare module 'workbox-cli/build/lib/read-config.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/read-config'>;
}
declare module 'workbox-cli/build/lib/run-wizard.js' {
  declare module.exports: $Exports<'workbox-cli/build/lib/run-wizard'>;
}
