version: "3.9"

services:
    donut_app:
        container_name: ${DOCKER_CONTAINER_NAME}
        build:
            context: ../../
            dockerfile: ./config/docker/dev.Dockerfile
        image: ${DOCKER_TAG}-dev
        volumes:
            - ../../src:/code/src
            # need provide .env file to container
            # with actual used port
            - ../../.env:/code/.env
        ports:
            # get variable from .env file automatically
            - ${PORT}:${PORT}
