version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm test
            - run: npm lint
            - run: npm check-types
workflows:
    build-and-test:
      jobs:
        - test