version: 2.1

orbs:
  node: circleci/node@4.1.0

commands:
    initial:
        steps:
        - checkout
        - run:
            name: Update repo
            command: sudo apt-get update
        - run:
            name: Install tools
            command: |
                sudo apt-get install libtool \
                    automake \
                    autoconf \
                    libpng-dev \
                    libjpeg-turbo8
        - run:
            name: Run ldconfig
            command: sudo ldconfig
        - run:
            name: Install Dependencies
            command: yarn install --immutable
        - persist_to_workspace:
            root: ./
            paths:
                - ./
    build:
        steps:
        - attach_workspace:
            at: ./
        - run: 
            name: Setting Environment
            command: cp .env.example .env
        - run: 
            name: Building production version
            command: yarn bundle
        - run: ls -lah
        - run: ls -lah logs
        - run: cat ./logs/bundle_errors_2.log
        - run: cat ./logs/bundle_errors_1.log

jobs:
    setup:
        executor: 
            name: node/default
        steps:
        - initial
    build: 
        executor: 
            name: node/default
        steps:
        - checkout
        - build
        
    test:
        executor: 
            name: node/default
        steps:
        - checkout
        - attach_workspace:
            at: ./
        - run: 
            name: Run CI  
            command: yarn ci

workflows:
    version: 2
    build-and-test:
        jobs:
        - setup
        - build:
            requires:
                - setup
        - test:
            requires:
                - setup