version: 2.1

orbs:
  node: circleci/node@4.1.0

commands:
    initial-dev:
        steps:
        - checkout
        - run:
            name: Install Dependencies
            command: yarn install --immutable
        - persist_to_workspace:
            root: ./
            paths:
                - ./
    initial-prod: 
        steps:
        - checkout
        - run:
            name: Install Dependencies
            command: yarn install --immutable
        - persist_to_workspace:
            root: ./
            paths:
                - ./
    build:
        steps:
        - attach_workspace:
            at: ./
        - run: 
            name: Setting Environment
            command: cp .env.example .env
        - run: 
            name: Building production version
            command: yarn bundle

jobs:
    setup-prod:
        executor: 
            name: node/default
        steps:
        - initial-prod
    setup-dev:
        executor: 
            name: node/default
        steps:
        - initial-dev
    build: 
        executor: 
            name: node/default
        steps:
        - checkout
        - build
    test:
        executor: 
            name: node/default
        steps:
        - checkout
        - attach_workspace:
            at: ./
        - run: 
            name: Run CI  
            command: yarn ci

workflows:
    version: 2
    build-and-test:
        jobs:
        - setup-dev
        - setup-prod
        - build:
            requires:
                - setup-prod
        - test:
            requires:
                - setup-dev