version: 2.1

orbs:
  node: circleci/node@1.1.6

commands:
    initial: 
        steps:
        - checkout
        - run: 
            name: Instal dependencies
            command: npm i
        - persist_to_workspace:
            root: ./
            paths:
                - ./
    build:
        steps:
        - attach_workspace:
            at: ./
        - run: 
            name: Setting Environment
            command: cp .env.example .env
        - run: 
            name: Building production version
            command: npm run build:prod

jobs:
    setup:
        executor: node/default
        steps:
        - initial
    build: 
        executor: node/default
        steps:
        - checkout
        - node/with-cache:
            steps:
            - build
    test:
        executor: node/default
        steps:
        - checkout
        - node/with-cache:
            steps:
            - attach_workspace:
                at: ./
            - run: 
                name: Run CI  
                command: npm run ci

workflows:
    version: 2
    build-and-test:
        jobs:
        - setup
        - build:
            requires:
                - setup
        - test:
            requires:
                - setup