version: 2.1

commands:
    initial:
        steps:
        - checkout
        - run:
            name: Install Dependencies
            command: yarn install --immutable
        - persist_to_workspace:
            root: ./
            paths:
                - ./
    build:
        steps:
        - attach_workspace:
            at: ./
        - run: 
            name: Setting Environment
            command: cp .env.example .env
        - run: 
            name: Building production version
            command: yarn bundle
        - run: 
            name: Echo build logs
            command: cat ./logs/bundle_errors_1.log
        - run: 
            name: Echo build logs
            command: cat ./logs/bundle_errors_2.log

jobs:
    setup:
        docker:
            - image: node:15.8.0
        steps:
        - initial
    build: 
        docker:
            - image: node:15.8.0
        steps:
        - checkout
        - build
        
    test:
        docker:
            - image: node:15.8.0
        steps:
        - checkout
        - attach_workspace:
            at: ./
        - run: 
            name: Run CI  
            command: yarn ci

workflows:
    version: 2
    build-and-test:
        jobs:
        - setup
        - build:
            requires:
                - setup
        - test:
            requires:
                - setup