version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build: 
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cp .env.example .env
            - run: npm install
            - run: npm run build:prod:server
            - run: npm run build:prod:client
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test
            - run: npm run lint
            - run: npm run check-types
workflows:
    build-and-test:
      jobs:
        - build
        - test