version: 2.1

orbs:
  node: circleci/node@4.1.0

commands:
    initial: 
        steps:
        - checkout
        - node/install-packages:
            override-ci-command: npm ci --production
        - persist_to_workspace:
            root: ./
            paths:
                - ./
    build:
        steps:
        - attach_workspace:
            at: ./
        - run: 
            name: Setting Environment
            command: cp .env.example .env
        - run: 
            name: Building production version
            command: npm run build:prod

jobs:
    setup:
        executor: 
            name: node/default
            tag: "12.19.0"
        steps:
        - initial
    build: 
        executor: 
            name: node/default
            tag: "12.19.0"
        steps:
        - checkout
        - build
    test:
        executor: 
            name: node/default
            tag: "12.19.0"
        steps:
        - checkout
        - attach_workspace:
            at: ./
        - run: 
            name: Run CI  
            command: npm run ci

workflows:
    version: 2
    build-and-test:
        jobs:
        - setup
        - build:
            requires:
                - setup
        - test:
            requires:
                - setup