version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
    setup:
        executor: node/default
        steps:
        - checkout
        - run: npm i
        - persist_to_workspace:
            root: ./
            paths:
                - ./
    build: 
        executor: node/default
        steps:
        - checkout
        - node/with-cache:
            steps:
            - attach_workspace:
                at: ./
            - run: 
                name: Setting Environment
                command: cp .env.example .env
            - run: 
                name: Building production version
                command: npm run build:prod
    test:
        executor: node/default
        steps:
        - checkout
        - node/with-cache:
            steps:
            - attach_workspace:
                at: ./
            - run: 
                name: Run CI  
                command: npm run ci
workflows:
    version: 2
    build-and-test:
        jobs:
        - setup
        - build:
            requires:
                - setup
        - test:
            requires:
                - setup