version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  setup:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
            root: ./
            paths:
                - ./
  build: 
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ./
            - run: cp .env.example .env
            - run: npm run build:prod:server
            - run: npm run build:prod:client
  test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ./
            - run: 
                name: Run CI  
                command: bash ./scripts/ci.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - build:
          requires:
              - setup
      - test:
          requires:
              - setup