version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - run: npm install
  build: 
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cp .env.example .env
            - run: npm run build:prod:server
            - run: npm run build:prod:client
  test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: bash ./scripts/ci.sh
            # - run: npm run test
            # - run: npm run lint
            # - run: npm run check-types
workflows:
  version: 2
  build-and-test:
    jobs:
      - install_dependencies
      - build:
          requires:
              - install_dependencies
      - test:
          requires:
              - install_dependencies