export enum KeyCodes {
	Escape = 'Escape',
	Backspace = 'Backspace',
	Tab = 'Tab',
	Enter = 'Enter',
	Space = 'Space',

	ControlLeft = 'ControlLeft',
	ControlRight = 'ControlRight',
	AltLeft = 'AltLeft',
	AltRight = 'AltRight',
	ShiftLeft = 'ShiftLeft',
	ShiftRight = 'ShiftRight',
	MetaLeft = 'MetaLeft',
	MetaRight = 'MetaRight',

	// Firefox
	OSLeft = 'OSLeft',
	OSRight = 'OSRight',
	CapsLock = 'CapsLock',

	Pause = 'Pause',
	ScrollLock = 'ScrollLock',
	PrintScreen = 'PrintScreen',
	NumLock = 'NumLock',
	Insert = 'Insert',
	Delete = 'Delete',

	ArrowUp = 'ArrowUp',
	ArrowDown = 'ArrowDown',
	ArrowLeft = 'ArrowLeft',
	ArrowRight = 'ArrowRight',

	Numpad1 = 'Numpad1',
	Numpad2 = 'Numpad2',
	Numpad3 = 'Numpad3',
	Numpad4 = 'Numpad4',
	Numpad5 = 'Numpad5',
	Numpad6 = 'Numpad6',
	Numpad7 = 'Numpad7',
	Numpad8 = 'Numpad8',
	Numpad9 = 'Numpad9',
	Numpad0 = 'Numpad0',
	NumpadAdd = 'NumpadAdd',
	NumpadSubtract = 'NumpadSubtract',
	NumpadMultiply = 'NumpadMultiply',
	NumpadDivide = 'NumpadDivide',
	NumpadDecimal = 'NumpadDecimal',
	NumpadEqual = 'NumpadEqual',
	NumpadEnter = 'NumpadEnter',

	Minus = 'Minus',
	Plus = 'Plus',
	Equal = 'Equal',
	Period = 'Period',
	BracketLeft = 'BracketLeft',
	BracketRight = 'BracketRight',

	F1 = 'F1',
	F2 = 'F2',
	F3 = 'F3',
	F4 = 'F4',
	F5 = 'F5',
	F6 = 'F6',
	F7 = 'F7',
	F8 = 'F8',
	F9 = 'F9',
	F10 = 'F10',
	F11 = 'F11',
	F12 = 'F12',

	KeyA = 'KeyA',
	KeyB = 'KeyB',
	KeyC = 'KeyC',
	KeyD = 'KeyD',
	KeyE = 'KeyE',
	KeyF = 'KeyF',
	KeyG = 'KeyG',
	KeyH = 'KeyH',
	KeyI = 'KeyI',
	KeyJ = 'KeyJ',
	KeyK = 'KeyK',
	KeyM = 'KeyM',
	KeyN = 'KeyN',
	KeyO = 'KeyO',
	KeyP = 'KeyP',
	KeyQ = 'KeyQ',
	KeyR = 'KeyR',
	KeyT = 'KeyT',
	KeyU = 'KeyU',
	KeyV = 'KeyV',
	KeyW = 'KeyW',
	KeyX = 'KeyX',
	KeyY = 'KeyY',
	KeyZ = 'KeyZ',

	Semicolon = 'Semicolon',
	Quote = 'Quote',
	Backquote = 'Backquote',
	Backslash = 'Backslash',
	Slash = 'Slash',
	Comma = 'Comma',

	Digit1 = 'Digit1',
	Digit2 = 'Digit2',
	Digit3 = 'Digit3',
	Digit4 = 'Digit4',
	Digit5 = 'Digit5',
	Digit6 = 'Digit6',
	Digit7 = 'Digit7',
	Digit8 = 'Digit8',
	Digit9 = 'Digit9',
	Digit0 = 'Digit0'
}
