name: CodeCov

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install cache
              uses: actions/cache@v3
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: |
                      .yarn/cache
                      .yarn/unplugged
                      .yarn/build-state.yml
                      .yarn/install-state.gz
                      .pnp.cjs
                      .pnp.loader.mjs
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn

            - name: Run tests
              run: yarn test:coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
