name: Deploy

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Copy .env
              run: cp .env.example .env

            - name: Paste secrets value to .env
              run: |
                  dotenv=$(cat .env)
                  newenv=${dotenv/APP_VERSION=/APP_VERSION="$secrets.APP_VERSION"}
                  echo $newenv >> .env

            - name: Generate public html
              run: sh app_vesrsion.sh

            - name: Debug
              run: cat index.html
