name: Prod Docker

on: [push, pull_request]

jobs:
    build_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Generate .env
              run: |
                  cat <<- EOF > .env
                    # server config
                    HOST=0.0.0.0
                    PORT=3000

                    # docker config
                    DOCKER_TAG="donut-app"
                    DOCKER_PROD_CONFIG_PATH="./config/docker/prod.Dockerfile"
                    DOCKER_CONTAINER_NAME="donut-app-container"

                    KILL_ON_READY=true

                  EOF

            - name: Caching docker layer
              uses: satackey/action-docker-layer-caching@v0.0.11
              continue-on-error: true

            - name: Build prod.Dockerfile
              run: make build-image

            - name: Check server running
              run: make run-container
